spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          nominatimClient:
            connectTimeout: 2000
            readTimeout: 3000

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}_${ENVIRONMENT}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: ${PORT}
  threads:
    virtual:
      enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - feign.FeignException.FeignServerException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      analyticsService: #Its going to be activated and deactivated inside aplication
        waitDurationInOpenState: 10000ms
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 1
      paymentService:
        baseConfig: default
        failureRateThreshold: 25
        slowCallDurationThreshold: 7000ms
        slowCallRateThreshold: 80
      publisherService:
        baseConfig: default
        failureRateThreshold: 50
        slowCallDurationThreshold: 40000ms
        slowCallRateThreshold: 40