spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:sqlite:payments.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: ${PORT}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - feign.FeignException.FeignServerException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      nookio-api:
        baseConfig: default
        failureRateThreshold: 50
      nookio-analytics-api:
        baseConfig: default
        failureRateThreshold: 50
