spring:
  application:
    name: nookio-api
    version: 0.1.0-SNAPSHOT
  cloud:
    openfeign:
      client:
        config:
          nominatimClient:
            connectTimeout: 2000
            readTimeout: 3000
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}_${ENVIRONMENT}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
server:
  port: ${PORT}
  threads:
    virtual:
      enabled: true

clients:
  api-id: ${API_ID}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}